export const topDealTag = "https://www.backpackerdeals.com/imagesv3/icon-last-minute.png"

export const activities = { 
  australia: {
    index: [
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/tasmania-multi-day-tour-1.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/famous-5-day-adventure-west-east-coast-of-tasmania.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/alice-springs-to-alice-springs-uluru-tour-3-days-2-nights-deals.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/83147cf84076dbce62f75254479bed066214b8f150cba85e9993096083402391.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/0ce7057fa7760ceeeac0b0683cd518483e3e2903.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/13552d9e9ab3afbbfc76d133e97fcdac089b3430262e2b6c2350304c590b57a8.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/kings-canyon-rim-walk.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/great-ocean-road-tour-from-melbourne.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/one-day-grampians-national-park-kangaroos-tour.JPG",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/yarra-valley-wine-tour-from-melbourne.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/figure-8-pools-coastal-adventure-hike.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/tasmania-multi-day-tour-1.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/great-ocean-road-day-tour-reverse.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/198bfde4a6c9bf66394f0429949342f62574c50db1709db6c34e0007778ac4bf.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/fraser-island-wilderness-camping-4wd-adventure-3-days-2-nights.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/e3e0c94c7d4713194b938b8f12da2640d99675eb58547058dd9d9405ea10d429.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/skydive-rockingham-14-000ft-tandem-skydiving.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/skydive-airlie-beach-14-000ft-tandem-skydiving.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/skydive-brisbane.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/5713313f6a6240ecfef90ffeec36230de348e725.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/27b45f5b40c4cf0abc8357327784947a04b163e7.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/cbace00326c13224b2a1fc657304b72dc5e96b9f.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/atlantic-clipper-3-days-2-night-whitsundays-trip.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/tasmania-multi-day-tour-1.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/famous-5-day-adventure-west-east-coast-of-tasmania.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/alice-springs-to-alice-springs-uluru-tour-3-days-2-nights-deals.jpg"
    ],
    uluru: [
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/alice-springs-to-alice-springs-uluru-tour-3-days-2-nights-deals.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/kings-canyon-rim-walk.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/deal_box_wide/uploads/deal/uluru-milky-way.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/kings-canyon-rim-walk.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/uluru-milky-way.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/uluru-ayers-rock-to-alice-springs-3-days-2-nights.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/alice-springs-to-alice-springs-uluru-tour-3-days-2-nights-deals.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/dot-painting-workshop-in-uluru.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/uluru-to-uluru-4-days.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/uluru-ayers-rock-to-uluru-2-days-1-night.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/fields-of-light-uluru.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/alice-springs-to-uluru-tour-ayers-rock-3-days-2-nights.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/alice-springs-to-darwin-express-tour-2-days-1-night.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/ayers-rock-discounts.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/uluru-kata-tjuta-helicopter-scenic-flight-1.png",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/7e53a9cc92ca492b45958f0a4e48aef40fff9cdad01f295c12191357558dcfa9.png",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/42b9894391d713ecc3541b0b7457acb46bb60e188a0f25e7d2cb64fa860c4cba.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/alice-springs-to-uluru-to-darwin-5-days-4-nights.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/outback-tours-uluru.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/alice-springs-to-adelaide-tour-deals.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/b1e5bcae2adc33076a4ae74571d1b479da628c50ae0b040a178cd598ace0e60c.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/red-centre-tour.jpg",
      "https://d2yqwx4q1fpmvo.cloudfront.net/media/cache/search_box_wide/uploads/deal/outback-uluru-tour.jpg",
    ]
  }
} 